# -*- coding: utf-8 -*-
"""RhythmRay_FullProject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMuGkrbtJmvmJq9vDLVOLFePAauvRan6
"""

!unzip "/content/ckpt_best .pt.zip"

!mv "/content/ckpt_best .pt.zip" "/content/ckpt_best.pt"

# ============================================================
# CELL 1: INSTALL & IMPORTS
# ============================================================
!pip install -q pyngrok streamlit
!pip install -q -U transformers peft accelerate bitsandbytes
!pip install -q torchvision scikit-learn opencv-python
!pip install -q wfdb tensorflow
!pip install -q sentencepiece protobuf
!pip install -q -U bitsandbytes accelerate sentencepiece protobuf

import os
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MEDGEMMA_ID = "google/gemma-2b-it"
LOCAL_DIR = "/content/google/gemma-2b-it"


bnb_llm = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MEDGEMMA_ID)
medgemma = AutoModelForCausalLM.from_pretrained(
    MEDGEMMA_ID,
    quantization_config=bnb_llm,
    device_map="auto"
)


os.makedirs(LOCAL_DIR, exist_ok=True)
tokenizer.save_pretrained(LOCAL_DIR)
medgemma.save_pretrained(LOCAL_DIR)
print(f"✅ Saved to {LOCAL_DIR}")
print(f"Files: {os.listdir(LOCAL_DIR)}")

import os, torch, numpy as np
import tensorflow as tf

# HuggingFace login for MedGemma(Use your token or leave it like this)
HF_TOKEN = ""



DRIVE_BASE       = r'/content'
CXR_CKPT         = f'{DRIVE_BASE}/ckpt_best.pt'
ECG_CKPT         = f'{DRIVE_BASE}/best_resnet1d.keras'
THRESHOLD_CKPT   = f'{DRIVE_BASE}/thresholds_ptbxl.json'
MEDGEMMA_DIR     = f'{DRIVE_BASE}/google/gemma-2b-it'

print("✅ Paths configured")
print(f"ECG Model  : {os.path.exists(ECG_CKPT)}")
print(f"CXR Model  : {os.path.exists(CXR_CKPT)}")
print(f"MedGemma   : {os.path.exists(MEDGEMMA_DIR)}")

# ============================================================
# CXR CLINICAL DICTIONARY
# ============================================================
CXR_CLINICAL = {
    "No Finding"        : "Normal chest X-ray. No acute cardiopulmonary process.",
    "Cardiomegaly"      : "Cardiomegaly present. Echocardiogram recommended.",
    "Hernia"            : "Hernia detected. Surgical evaluation may be required.",
    "Infiltration"      : "Pulmonary infiltrate detected. Consider pneumonia or aspiration.",
    "Nodule"            : "Pulmonary nodule identified. Follow-up CT recommended.",
    "Emphysema"         : "Emphysematous changes noted. Consistent with COPD.",
    "Effusion"          : "Pleural effusion present. Evaluate for heart failure or infection.",
    "Atelectasis"       : "Atelectasis noted. May indicate airway obstruction.",
    "Pleural_Thickening": "Pleural thickening noted.",
    "Pneumothorax"      : "Pneumothorax identified. Immediate clinical evaluation required.",
    "Mass"              : "Pulmonary mass detected. Urgent CT and oncology referral advised.",
    "Fibrosis"          : "Pulmonary fibrosis pattern. Pulmonology referral advised.",
    "Consolidation"     : "Consolidation present. Consistent with lobar pneumonia.",
    "Edema"             : "Pulmonary edema detected. Evaluate for heart failure.",
    "Pneumonia"         : "Pneumonia pattern detected. Clinical correlation and treatment advised."
}

# ============================================================
# ECG CLINICAL DICTIONARY
# ============================================================
ECG_CLINICAL = {
    "NORM": "Normal sinus rhythm. No acute ECG abnormalities.",
    "MI": "Myocardial infarction detected. Urgent cardiology evaluation required.",
    "STTC": "ST/T wave changes. Evaluate for ischemia or electrolyte abnormalities.",
    "CD": "Conduction disturbance. Consider bundle branch block or AV block.",
    "HYP": "Left ventricular hypertrophy. Echocardiogram recommended."
}

# ============================================================
# REPORT GENERATOR
# ============================================================
def generate_report(scan_type: str, diagnosis: str, confidence) -> str:
    if scan_type == "CXR":
        if diagnosis == "No Finding":
            note = CXR_CLINICAL.get("No Finding", "Normal chest X-ray.")
        else:
            labels = [l.strip() for l in diagnosis.split("+")]
            notes = [CXR_CLINICAL.get(l, f"Finding: {l}") for l in labels]
            note = " | ".join(notes)
    else:
        labels = [l.strip() for l in diagnosis.split("+")]
        notes = [ECG_CLINICAL.get(l, f"Finding: {l}") for l in labels]
        note = " | ".join(notes)

    prompt = f"""### Instruction:
You are a medical AI assistant. Based on the AI analysis result below,
write a concise clinical report in 3-4 sentences for the physician.

Scan Type: {scan_type}
AI Diagnosis: {diagnosis}
Max Confidence: {confidence}%
Clinical Notes: {note}

### Response:
"""
    inputs = tokenizer(prompt, return_tensors="pt").to(medgemma.device)
    with torch.no_grad():
        out = medgemma.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.3,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
    resp = tokenizer.decode(out[0], skip_special_tokens=True)
    return resp.split("### Response:")[-1].strip() \
           if "### Response:" in resp else resp

# ============================================================
# CXR MODEL — PyTorch
# ============================================================
from PIL import Image
import pickle

CXR_LABELS = [
    'Cardiomegaly', 'Hernia', 'Infiltration', 'Nodule', 'Emphysema',
    'Effusion', 'Atelectasis', 'Pleural_Thickening', 'Pneumothorax',
    'Mass', 'Fibrosis', 'Consolidation', 'Edema', 'Pneumonia'
]

def preprocess_cxr(image_path):
    # 1. Convert to Grayscale
    img = Image.open(image_path).convert('L')
    img = img.resize((224, 224))

    img = np.array(img).astype(np.float32)

    # 2. EXACT torchxrayvision normalization ([-1024, 1024] range)
    img = (img / 255.0) * 2048.0 - 1024.0

    # 3. Add Channel and Batch dimensions
    img = np.expand_dims(img, axis=0)  # -> (1, 224, 224)
    img = np.expand_dims(img, axis=0)  # -> (1, 1, 224, 224)

    return torch.from_numpy(img).float()

def load_cxr_model():
    """Load PyTorch CXR model."""
    if not os.path.exists(CXR_CKPT):
        raise FileNotFoundError(f"CXR model not found: {CXR_CKPT}")

    print(f"⏳ Loading CXR model from: {CXR_CKPT}")

    device_map = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    cxr_data = torch.load(CXR_CKPT, map_location=device_map, weights_only=False)

    # 1. Extract the model/state_dict and classes
    if isinstance(cxr_data, tuple) and len(cxr_data) == 2:
        model = cxr_data[0]
        class_names = cxr_data[1] if cxr_data[1] else CXR_LABELS
    elif isinstance(cxr_data, dict):
        # Check if it's a wrapper dict, otherwise assume the dict IS the state_dict
        if 'model' in cxr_data:
            model = cxr_data['model']
        elif 'state_dict' in cxr_data:
            model = cxr_data['state_dict']
        else:
            model = cxr_data # It's a raw state_dict!

        class_names = cxr_data.get('classes', CXR_LABELS)
    else:
        model = cxr_data
        class_names = CXR_LABELS


    if isinstance(model, dict):
        from torchvision import models
        import torch.nn as nn

        architecture = models.densenet121(pretrained=False)

        architecture.features.conv0 = nn.Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)

        num_classes = len(CXR_LABELS)
        architecture.classifier = nn.Linear(architecture.classifier.in_features, num_classes)

        clean_state_dict = {}
        for k, v in model.items():
            clean_key = k.replace('module.', '').replace('backbone.', '')
            clean_state_dict[clean_key] = v

        architecture.load_state_dict(clean_state_dict, strict=False)
        model = architecture

    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)

    print(f"✅ CXR model loaded on {device}")
    return model, class_names

def predict_cxr(image_path):
    """Predict with PyTorch CXR model."""
    model, class_names = load_cxr_model()
    img = preprocess_cxr(image_path).to(next(model.parameters()).device)

    with torch.no_grad():
        logits = model(img)
        probs = torch.sigmoid(logits).cpu().numpy()[0]

    thresholds = [0.5] * len(class_names)
    preds = np.array([1 if probs[i] >= thresholds[i] else 0 for i in range(len(class_names))])
    detected = [class_names[i] for i, p in enumerate(preds) if p == 1]

    if not detected:
        detected = [class_names[np.argmax(probs)]]

    main_diag = " + ".join(detected)
    max_conf = max(probs[i] * 100 for i in [class_names.index(d) for d in detected])
    all_probs = {class_names[i]: round(float(probs[i]) * 100, 1) for i in range(len(class_names))}

    return main_diag, round(float(max_conf), 1), all_probs

# ============================================================
# ECG ResNet1D MODEL
# ============================================================
import cv2
from scipy.signal import butter, filtfilt
from PIL import Image

SUPERCLASSES = ["NORM", "MI", "STTC", "CD", "HYP"]

def load_ecg_resnet1d():
    """Load our PTB-XL ResNet1D model."""
    if not os.path.exists(ECG_CKPT):
        raise FileNotFoundError(f"ResNet1D model not found: {ECG_CKPT}")

    model = tf.keras.models.load_model(ECG_CKPT, compile=False)


    thresholds = [0.5] * 5
    if os.path.exists(THRESHOLD_CKPT):
        import json
        with open(THRESHOLD_CKPT, 'r') as f:
            t = json.load(f)
            thresholds = [t.get(cls, 0.5) for cls in SUPERCLASSES]

    return model, thresholds

def ecg_image_to_signal(image_path, target_length=5000):
    """Convert ECG image to 12-lead signal (same digitizer as original)."""
    img = cv2.imread(image_path)
    if img is None:
        return None

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)


    mask_r1 = cv2.inRange(hsv, (0, 50, 50), (10, 255, 255))
    mask_r2 = cv2.inRange(hsv, (170, 50, 50), (180, 255, 255))
    mask_blue = cv2.inRange(hsv, (90, 30, 150), (130, 255, 255))
    grid_mask = cv2.bitwise_or(cv2.bitwise_or(mask_r1, mask_r2), mask_blue)

    clean = gray.copy()
    clean[grid_mask > 0] = 255
    clean = cv2.equalizeHist(clean)

    _, binary = cv2.threshold(clean, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
    binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)


    row_h = h // 3
    col_w = w // 4
    leads_coords = [
        (r * row_h, (r + 1) * row_h, c * col_w, (c + 1) * col_w)
        for r in range(3) for c in range(4)
    ]

    def extract_lead(binary_img, y1, y2, x1, x2):
        region = binary_img[y1:y2, x1:x2]
        rh, rw = region.shape
        baseline = rh / 2
        signal = np.zeros(rw)
        for col in range(rw):
            px = np.where(region[:, col] > 0)[0]
            if len(px) > 0:
                signal[col] = baseline - np.average(px, weights=region[:, col][px].astype(float))
        if signal.std() > 1e-6:
            signal = (signal - signal.mean()) / signal.std()
        signal_resized = cv2.resize(signal.reshape(1, -1).astype(np.float32), (target_length, 1)).flatten()
        return signal_resized

    def butter_lowpass(data, cutoff=40, fs=500, order=4):
        try:
            nyq = 0.5 * fs
            b, a = butter(order, cutoff / nyq, btype="low", analog=False)
            return filtfilt(b, a, data)
        except:
            return data

    ecg_12 = np.zeros((12, target_length), dtype=np.float32)
    for i, (y1, y2, x1, x2) in enumerate(leads_coords[:12]):
        ecg_12[i] = butter_lowpass(extract_lead(binary, y1, y2, x1, x2))

    return ecg_12

def load_signal_file(uploaded_file, target_length=5000):
    """Load signal from .npy or .csv files."""
    fname = uploaded_file.name.lower()

    if fname.endswith(".npy"):
        import io
        signal = np.load(io.BytesIO(uploaded_file.getvalue()))

        if signal.ndim == 3 and signal.shape[0] == 1:
            signal = signal.squeeze(0)
    elif fname.endswith(".csv"):
        import pandas as pd
        signal = pd.read_csv(uploaded_file).values
    else:
        return None


    if signal.ndim == 2 and signal.shape[0] != 12:
        signal = signal.T

    signal = signal[:12, :target_length].astype(np.float32)
    if signal.shape[1] < target_length:
        pad = np.zeros((12, target_length - signal.shape[1]), dtype=np.float32)
        signal = np.hstack([signal, pad])


    for i in range(12):
        mean = signal[i].mean()
        std = signal[i].std()
        if std > 0:
            signal[i] = (signal[i] - mean) / std

    return signal

def predict_ecg(signal_12lead):
    """Predict with CNN."""
    model, thresholds = load_ecg_resnet1d()


    x = np.transpose(signal_12lead, (1, 0))
    x = np.expand_dims(x, axis=0).astype(np.float32)

    # Predict
    probs = model.predict(x, verbose=0)[0]

    # Apply thresholds
    preds = np.array([1 if probs[i] >= thresholds[i] else 0 for i in range(5)])

    # Get detected classes
    detected = [SUPERCLASSES[i] for i, p in enumerate(preds) if p == 1]
    if not detected:
        detected = [SUPERCLASSES[np.argmax(probs)]]

    main_diag = " + ".join(detected)
    max_conf = max(probs[i] * 100 for i in [SUPERCLASSES.index(d) for d in detected])

    all_probs = {SUPERCLASSES[i]: round(float(probs[i]) * 100, 1) for i in range(5)}

    return main_diag, round(float(max_conf), 1), all_probs

# ============================================================
# MAIN ANALYSIS FUNCTION
# ============================================================
def analyze_full(image_path: str = None, signal_file=None, scan_type: str = "ECG") -> dict:
    if scan_type == "CXR":
        result = predict_cxr(image_path)
    else:

        if signal_file is not None:
            signal = load_signal_file(signal_file)
            if signal is not None:
                result = predict_ecg(signal)
            else:
                result = ("Error", 0, {})
        elif image_path is not None:
            signal = ecg_image_to_signal(image_path)
            if signal is not None:
                result = predict_ecg(signal)
            else:
                result = ("Error", 0, {})
        else:
            result = ("Error", 0, {})

    report = generate_report(scan_type, result[0], result[1])

    return {
        "scan_type" : scan_type,
        "diagnosis" : result[0],
        "confidence": result[1],
        "all_probs" : result[2],
        "report"    : report
    }

print("Ready")

# ============================================================
# STREAMLIT APP
# ============================================================
import subprocess, time
from pyngrok import ngrok

subprocess.run(["pkill", "-f", "streamlit"], capture_output=True)
subprocess.run(["pkill", "-f", "ngrok"], capture_output=True)
time.sleep(2)

NGROK_TOKEN = ""
subprocess.run(["ngrok", "config", "add-authtoken", NGROK_TOKEN])

APP_CODE = """
import streamlit as st
import torch
import torch.nn as nn
import cv2
import numpy as np
import pandas as pd
import pickle
from torchvision import models as tv_models, transforms
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from PIL import Image
from scipy.signal import butter, filtfilt
import tempfile, os, time
import tensorflow as tf

st.set_page_config(page_title="RhythmRay AI", page_icon="🫀", layout="wide")

st.markdown('''
<style>
[data-testid="stDecoration"], .stDeployButton { display:none; }
.stButton>button {
    background: linear-gradient(90deg,#00C9FF,#92FE9D);
    color:#004d40; border:none; font-weight:bold;
    height:45px; width:100%;
}
.result-card {
    background:#1e1e1e; border-radius:12px; padding:20px;
    margin:10px 0; border-left:5px solid #00C9FF; color:white;
}
.prob-bar {
    background:#333; border-radius:5px; margin:3px 0;
    padding:3px 8px; font-size:13px; color:white;
}
</style>
''', unsafe_allow_html=True)

BASE_DIR           = "/content"
CXR_CKPT           = f"{BASE_DIR}/ckpt_best.pt"
ECG_CKPT           = f"{BASE_DIR}/best_resnet1d.keras"
THRESHOLD_CKPT     = f"{BASE_DIR}/thresholds_ptbxl.json"
GEMMA_ID           = "/content/google/gemma-2b-it"  # LOCAL
device             = "cuda" if torch.cuda.is_available() else "cpu"

CXR_LABELS = [
    'Cardiomegaly', 'Hernia', 'Infiltration', 'Nodule', 'Emphysema',
    'Effusion', 'Atelectasis', 'Pleural_Thickening', 'Pneumothorax',
    'Mass', 'Fibrosis', 'Consolidation', 'Edema', 'Pneumonia'
]

CXR_CLINICAL = {
    "No Finding"        : "Normal chest X-ray. No acute cardiopulmonary process.",
    "Cardiomegaly"      : "Cardiomegaly present. Echocardiogram recommended.",
    "Hernia"            : "Hernia detected. Surgical evaluation may be required.",
    "Infiltration"      : "Pulmonary infiltrate detected. Consider pneumonia or aspiration.",
    "Nodule"            : "Pulmonary nodule identified. Follow-up CT recommended.",
    "Emphysema"         : "Emphysematous changes noted. Consistent with COPD.",
    "Effusion"          : "Pleural effusion present. Evaluate for heart failure or infection.",
    "Atelectasis"       : "Atelectasis noted. May indicate airway obstruction.",
    "Pleural_Thickening": "Pleural thickening noted.",
    "Pneumothorax"      : "Pneumothorax identified. Immediate clinical evaluation required.",
    "Mass"              : "Pulmonary mass detected. Urgent CT and oncology referral advised.",
    "Fibrosis"          : "Pulmonary fibrosis pattern. Pulmonology referral advised.",
    "Consolidation"     : "Consolidation present. Consistent with lobar pneumonia.",
    "Edema"             : "Pulmonary edema detected. Evaluate for heart failure.",
    "Pneumonia"         : "Pneumonia pattern detected. Clinical correlation and treatment advised."
}

ECG_CLINICAL = {
    "NORM": "Normal sinus rhythm. No acute ECG abnormalities.",
    "MI"  : "Myocardial infarction detected. Urgent cardiology evaluation required.",
    "STTC": "ST/T wave changes. Evaluate for ischemia or electrolyte abnormalities.",
    "CD"  : "Conduction disturbance. Consider bundle branch block or AV block.",
    "HYP" : "Left ventricular hypertrophy. Echocardiogram recommended."
}

SUPERCLASSES = ["NORM", "MI", "STTC", "CD", "HYP"]

@st.cache_resource
def load_gemma():
    bnb = BitsAndBytesConfig(
        load_in_4bit=True, bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16, bnb_4bit_use_double_quant=True
    )
    tok = AutoTokenizer.from_pretrained(GEMMA_ID)
    llm = AutoModelForCausalLM.from_pretrained(GEMMA_ID, quantization_config=bnb, device_map="auto")
    return tok, llm.eval()

def make_report(scan, diagnosis, conf):
    tok, llm = load_gemma()
    if scan == "CXR":
        if diagnosis == "No Finding":
            note = CXR_CLINICAL.get("No Finding", "Normal chest X-ray.")
        else:
            labels = [l.strip() for l in diagnosis.split("+")]
            notes = [CXR_CLINICAL.get(l, f"Finding: {l}") for l in labels]
            note = " | ".join(notes)
    else:
        labels = [l.strip() for l in diagnosis.split("+")]
        notes = [ECG_CLINICAL.get(l, f"Finding: {l}") for l in labels]
        note = " | ".join(notes)
    prompt_lines = [
        "### Instruction:",
        "You are a medical AI assistant. Based on the AI analysis result below,",
        "write a concise clinical report in 3-4 sentences for the physician.",
        "",
        f"Scan Type: {scan}",
        f"AI Diagnosis: {diagnosis}",
        f"Max Confidence: {conf}%",
        f"Clinical Notes: {note}",
        "",
        "### Response:",
        ""
    ]
    prompt = "\\n".join(prompt_lines)
    inp = tok(prompt, return_tensors="pt").to(llm.device)
    with torch.no_grad():
        out = llm.generate(**inp, max_new_tokens=150, temperature=0.3,
                           do_sample=True, pad_token_id=tok.eos_token_id)
    r = tok.decode(out[0], skip_special_tokens=True)
    return r.split("### Response:")[-1].strip() if "### Response:" in r else r

def preprocess_cxr(image_path):
    # 1. Convert to Grayscale
    img = Image.open(image_path).convert('L')
    img = img.resize((224, 224))

    img = np.array(img).astype(np.float32)

    # 2. EXACT torchxrayvision normalization ([-1024, 1024] range)
    img = (img / 255.0) * 2048.0 - 1024.0

    # 3. Add Channel and Batch dimensions
    img = np.expand_dims(img, axis=0)  # -> (1, 224, 224)
    img = np.expand_dims(img, axis=0)  # -> (1, 1, 224, 224)

    return torch.from_numpy(img).float()

@st.cache_resource
def load_cxr():
    if not os.path.exists(CXR_CKPT):
        st.error(f"🚨 CXR model not found: {CXR_CKPT}")
        st.stop()

    device_map = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    cxr_data = torch.load(CXR_CKPT, map_location=device_map, weights_only=False)

    if isinstance(cxr_data, tuple) and len(cxr_data) == 2:
        model = cxr_data[0]
        class_names = cxr_data[1] if cxr_data[1] else CXR_LABELS
    elif isinstance(cxr_data, dict):
        if 'model' in cxr_data:
            model = cxr_data['model']
        elif 'state_dict' in cxr_data:
            model = cxr_data['state_dict']
        else:
            model = cxr_data
        class_names = cxr_data.get('classes', CXR_LABELS)
    else:
        model = cxr_data
        class_names = CXR_LABELS

    if isinstance(model, dict):
        from torchvision import models
        import torch.nn as nn

        architecture = models.densenet121(pretrained=False)
        architecture.features.conv0 = nn.Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
        num_classes = len(CXR_LABELS)
        architecture.classifier = nn.Linear(architecture.classifier.in_features, num_classes)

        clean_state_dict = {}
        for k, v in model.items():
            clean_key = k.replace('module.', '').replace('backbone.', '')
            clean_state_dict[clean_key] = v

        architecture.load_state_dict(clean_state_dict, strict=False)
        model = architecture

    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    print("✅ CXR model loaded")

    thresholds = [0.5] * len(class_names)
    return model, class_names, thresholds

def run_cxr(path):
    model, class_names, thresholds = load_cxr()
    img = preprocess_cxr(path).to(next(model.parameters()).device)

    with torch.no_grad():
        logits = model(img)
        probs = torch.sigmoid(logits).cpu().numpy()[0]

    preds = np.array([1 if probs[i] >= thresholds[i] else 0 for i in range(len(class_names))])
    detected = [class_names[i] for i, p in enumerate(preds) if p == 1]
    if not detected:
        detected = [class_names[np.argmax(probs)]]
    main_diag = " + ".join(detected)
    max_conf  = max(probs[i] * 100 for i in [class_names.index(d) for d in detected])
    all_probs = {class_names[i]: round(float(probs[i]) * 100, 1) for i in range(len(class_names))}
    return main_diag, round(float(max_conf), 1), all_probs

@st.cache_resource
def load_ecg_resnet1d():
    if not os.path.exists(ECG_CKPT):
        st.error(f"🚨 ResNet1D model not found: {ECG_CKPT}")
        st.stop()
    model = tf.keras.models.load_model(ECG_CKPT, compile=False)
    thresholds = [0.5] * 5
    if os.path.exists(THRESHOLD_CKPT):
        import json
        with open(THRESHOLD_CKPT, 'r') as f:
            t = json.load(f)
            thresholds = [t.get(cls, 0.5) for cls in SUPERCLASSES]
    return model, thresholds

def ecg_image_to_signal(image_path, target_length=5000):
    img = cv2.imread(image_path)
    if img is None:
        return None
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape
    hsv  = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    mask_r1   = cv2.inRange(hsv, (0, 50, 50), (10, 255, 255))
    mask_r2   = cv2.inRange(hsv, (170, 50, 50), (180, 255, 255))
    mask_blue = cv2.inRange(hsv, (90, 30, 150), (130, 255, 255))
    grid_mask = cv2.bitwise_or(cv2.bitwise_or(mask_r1, mask_r2), mask_blue)
    clean = gray.copy()
    clean[grid_mask > 0] = 255
    clean = cv2.equalizeHist(clean)
    _, binary = cv2.threshold(clean, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
    binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)
    row_h = h // 3
    col_w = w // 4
    leads_coords = [
        (r*row_h, (r+1)*row_h, c*col_w, (c+1)*col_w)
        for r in range(3) for c in range(4)
    ]
    def extract_lead(binary_img, y1, y2, x1, x2):
        region   = binary_img[y1:y2, x1:x2]
        rh, rw   = region.shape
        baseline = rh / 2
        signal   = np.zeros(rw)
        for col in range(rw):
            px = np.where(region[:, col] > 0)[0]
            if len(px) > 0:
                signal[col] = baseline - np.average(px, weights=region[:, col][px].astype(float))
        if signal.std() > 1e-6:
            signal = (signal - signal.mean()) / signal.std()
        return cv2.resize(signal.reshape(1,-1).astype(np.float32), (target_length,1)).flatten()
    def butter_lowpass(data, cutoff=40, fs=500, order=4):
        try:
            nyq = 0.5 * fs
            b, a = butter(order, cutoff/nyq, btype="low", analog=False)
            return filtfilt(b, a, data)
        except:
            return data
    ecg_12 = np.zeros((12, target_length), dtype=np.float32)
    for i, (y1,y2,x1,x2) in enumerate(leads_coords[:12]):
        ecg_12[i] = butter_lowpass(extract_lead(binary, y1,y2,x1,x2))
    return ecg_12

def load_signal_file(uploaded_file, target_length=5000):
    fname = uploaded_file.name.lower()
    if fname.endswith(".npy"):
        import io
        signal = np.load(io.BytesIO(uploaded_file.getvalue()))
        if signal.ndim == 3 and signal.shape[0] == 1:
            signal = signal.squeeze(0)
    elif fname.endswith(".csv"):
        signal = pd.read_csv(uploaded_file).values
    else:
        return None
    if signal.ndim == 2 and signal.shape[0] != 12:
        signal = signal.T
    signal = signal[:12, :target_length].astype(np.float32)
    if signal.shape[1] < target_length:
        pad    = np.zeros((12, target_length - signal.shape[1]), dtype=np.float32)
        signal = np.hstack([signal, pad])
    for i in range(12):
        mean = signal[i].mean()
        std  = signal[i].std()
        if std > 0:
            signal[i] = (signal[i] - mean) / std
    return signal

def run_ecg(signal_tensor):
    model, thresholds = load_ecg_resnet1d()
    x     = np.transpose(signal_tensor, (1, 0))
    x     = np.expand_dims(x, axis=0).astype(np.float32)
    probs = model.predict(x, verbose=0)[0]
    preds = np.array([1 if probs[i] >= thresholds[i] else 0 for i in range(5)])
    detected = [SUPERCLASSES[i] for i, p in enumerate(preds) if p == 1]
    if not detected:
        detected = [SUPERCLASSES[np.argmax(probs)]]
    main_diag = " + ".join(detected)
    max_conf  = max(probs[i] * 100 for i in [SUPERCLASSES.index(d) for d in detected])
    all_probs = {SUPERCLASSES[i]: round(float(probs[i]) * 100, 1) for i in range(5)}
    return main_diag, round(float(max_conf), 1), all_probs

with st.sidebar:
    st.markdown("## 🫀 RhythmRay AI")
    st.markdown("---")
    scan_type = st.radio("Scan Type", ["ECG - Electrocardiogram", "CXR - Chest X-Ray"])
    st.markdown("---")
    st.markdown("### Team")
    for name in ["Yazan Alhusseini","Khaled Alsolami",
                 "Osama Alharbi","Thamer Alzahrani","Raad Aladli"]:
        st.markdown(f"- {name}")

st.title("RhythmRay AI")
st.caption("Advanced Multi-Label Diagnostic System for ECG & CXR")
st.markdown("---")

col1, col2 = st.columns([1, 1])

with col1:
    st.markdown("### Upload")
    uploaded_img = st.file_uploader(
        "Upload Medical Image (PNG/JPG)", type=["png","jpg","jpeg"]
    )
    if "ECG" in scan_type:
        st.markdown("**أو ارفع ملف إشارة رقمية (دقة أعلى)**")
        uploaded_signal = st.file_uploader(
            "ECG Signal File (NPY/CSV)", type=["npy","csv"]
        )
        if uploaded_signal:
            st.success("✅ تم رفع ملف الإشارة الرقمية — سيُستخدم للتحليل")
    else:
        uploaded_signal = None

    if uploaded_img:
        st.image(uploaded_img, use_container_width=True)

with col2:
    st.markdown("### Diagnosis Result")
    if uploaded_img or uploaded_signal:
        if st.button("Analyze Scan"):
            scan = "CXR" if "CXR" in scan_type else "ECG"

            with st.spinner("AI is analyzing..."):
                if scan == "CXR":
                    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as f:
                        f.write(uploaded_img.getvalue())
                        tmp = f.name
                    diag, conf, probs = run_cxr(tmp)
                    os.unlink(tmp)
                else:
                    if uploaded_signal:
                        signal_tensor = load_signal_file(uploaded_signal)
                        if signal_tensor is None:
                            st.error("❌ Failed to load signal file")
                            st.stop()
                        st.success("✅ Using raw signal file (highest accuracy)")
                        with st.expander("Debug: Signal Preview"):
                            import matplotlib.pyplot as plt
                            fig, axes = plt.subplots(12, 1, figsize=(14, 18))
                            for i in range(12):
                                axes[i].plot(signal_tensor[i], color='#00C9FF', linewidth=0.8)
                                axes[i].set_title(f'Lead {i+1}', fontsize=9, color='white')
                                axes[i].set_facecolor('#1e1e1e')
                                axes[i].tick_params(colors='white')
                                axes[i].spines['bottom'].set_color('white')
                                axes[i].spines['top'].set_color('white')
                                axes[i].spines['left'].set_color('white')
                                axes[i].spines['right'].set_color('white')
                            fig.patch.set_facecolor('#1e1e1e')
                            plt.tight_layout()
                            st.pyplot(fig)
                            plt.close(fig)
                    else:
                        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as f:
                            f.write(uploaded_img.getvalue())
                            tmp = f.name
                        signal_tensor = ecg_image_to_signal(tmp)
                        os.unlink(tmp)
                        if signal_tensor is None:
                            st.error("❌ Failed to process ECG image")
                            st.stop()
                        st.warning("⚠️ Image digitization (approximate). For best accuracy, upload .npy file.")

                    diag, conf, probs = run_ecg(signal_tensor)

            report = make_report(scan, diag, conf)

            st.markdown(f'''
            <div class="result-card">
                <h3 style="color:#92FE9D;">Primary Findings:<br>{diag}</h3>
                <p>Confidence Level: <b>{conf}%</b></p>
            </div>
            ''', unsafe_allow_html=True)

            with st.expander("Detailed Probabilities"):
                for label, prob in sorted(probs.items(), key=lambda x: x[1], reverse=True)[:10]:
                    st.markdown(f'''
                    <div class="prob-bar">
                        {label}: <b>{prob}%</b>
                        <div style="background:#00C9FF;height:6px;
                             width:{min(prob,100)}%;border-radius:3px;margin-top:3px">
                        </div>
                    </div>
                    ''', unsafe_allow_html=True)

            st.markdown("### 📝 AI Medical Report")
            st.info(report)
    else:
        st.info("👆 Upload an image or signal file to begin analysis.")
"""

with open("/content/app.py", "w", encoding="utf-8") as f:
    f.write(APP_CODE)

print("✅ app.py written successfully")

proc = subprocess.Popen(
    ["streamlit", "run", "/content/app.py",
     "--server.port=8501", "--server.headless=true"],
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
)
time.sleep(5)

tunnel = ngrok.connect(8501)
print("=" * 50)
print("🚀 RhythmRay AI is LIVE at:")
print(f"   {tunnel.public_url}")
print("=" * 50)
